#Faça um programa que leia um número inteiro qualquer e mostra na tela a sua tabuada
n = int(input('Digite um número inteiro qualquer, que eu vou lhe mostrar a tabuada dele: '))
print("-="*12)
print(f'{n} x 1 = ',n)
print(f'{n} x 2 = ',n * 2)
print(f'{n} x 3 = ',n * 3)
print(f'{n} x 4 = ',n * 4)
print(f'{n} x 5 = ',n * 5)
print(f'{n} x 6 = ',n * 6)
print(f'{n} x 7 = ',n * 7)
print(f'{n} x 8 = ',n * 8)
print(f'{n} x 9 = ',n * 9)
print(f'{n} x 10 = ',n * 10)
print('=-'*12)