nome = str(input('Digite aqui o seu nome completo: ').strip())
print('Analisando seu nome...')
(str(input('Pressione "Enter" para continuar.')))
print(f'Seu nome em maiúsculas é {nome.upper()}')
print(f'Seu nome em minúsculas é {nome.lower()}')
print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
nome2 = len(nome) - nome.count(' ')
print(f'Seu nome tem {nome2} letras')
nome3 = nome.split()
print(f'Seu primeiro nome é {nome3[0]} e ele tem {len(nome3[0])} letras')
